# -*- coding: utf-8 -*-
"""Task_b_OverLay.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Xk9mYQDDcezfy52pn9QVqfeU77iaLPRg
"""

!wget https://raw.githubusercontent.com/kiranbeethoju/EU-CV-BottleDetector/main/Solution-1_b/Task-1b.png

import cv2
import numpy as np
import matplotlib.pyplot as plt 

def TextOverlay(input_image):
    threshold = 50
    input_image = np.max(input_image,axis=2)
    input_image[input_image<threshold] = 0
    input_image[input_image>threshold] = 255
    kernel_dilate = np.ones((5,5),np.uint8)
    input_image = cv2.dilate(input_image,kernel_dilate)
    return input_image
if __name__ == '__main__':  
    image = cv2.imread('Task-1b.png')
    output = TextOverlay(image)
    cv2.imwrite('Task-1b_Output.png', output)
    from google.colab.patches import cv2_imshow
    img = cv2.imread('Task-1b_Output.png', cv2.IMREAD_UNCHANGED)
    cv2_imshow(img)

from google.colab.patches import cv2_imshow
img = cv2.imread('simpons_text.png', cv2.IMREAD_UNCHANGED)
cv2_imshow(img)

